// Lista completa LC 116/2003 — usada em Config.jsx e OnboardingWizard.jsx
export const LC116 = [
  { cod:'1.01',  desc:'Análise e desenvolvimento de sistemas' },
  { cod:'1.02',  desc:'Programação' },
  { cod:'1.03',  desc:'Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação' },
  { cod:'1.04',  desc:'Elaboração de programas de computadores, inclusive de jogos eletrônicos' },
  { cod:'1.05',  desc:'Licenciamento ou cessão de direito de uso de programas de computação' },
  { cod:'1.06',  desc:'Assessoria e consultoria em informática' },
  { cod:'1.07',  desc:'Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas e bancos de dados' },
  { cod:'1.08',  desc:'Planejamento, confecção, manutenção e atualização de páginas eletrônicas' },
  { cod:'1.09',  desc:'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet (streaming)' },
  { cod:'2.01',  desc:'Serviços de pesquisas e desenvolvimento de qualquer natureza' },
  { cod:'3.02',  desc:'Exploração de salões de festas, centro de convenções, escritórios virtuais, stands, quadras esportivas, estádios, ginásios, auditórios, casas de shows, parques de diversões e congêneres' },
  { cod:'3.03',  desc:'Locação, sublocação, arrendamento, direito de passagem ou permissão de uso de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza' },
  { cod:'3.04',  desc:'Locação, sublocação, arrendamento, direito de passagem de aquoduto, ponte, túnel, porto e congêneres' },
  { cod:'3.05',  desc:'Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário' },
  { cod:'4.01',  desc:'Medicina e biomedicina' },
  { cod:'4.02',  desc:'Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultrassonografia, ressonância magnética, radiologia, tomografia e congêneres' },
  { cod:'4.03',  desc:'Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres' },
  { cod:'4.04',  desc:'Instrumentação cirúrgica' },
  { cod:'4.05',  desc:'Acupuntura' },
  { cod:'4.06',  desc:'Enfermagem, inclusive serviços auxiliares' },
  { cod:'4.07',  desc:'Serviços farmacêuticos' },
  { cod:'4.08',  desc:'Terapia ocupacional, fisioterapia e fonoaudiologia' },
  { cod:'4.09',  desc:'Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental' },
  { cod:'4.10',  desc:'Nutrição' },
  { cod:'4.11',  desc:'Obstetrícia' },
  { cod:'4.12',  desc:'Odontologia' },
  { cod:'4.13',  desc:'Ortóptica' },
  { cod:'4.14',  desc:'Próteses sob encomenda' },
  { cod:'4.15',  desc:'Psicanálise' },
  { cod:'4.16',  desc:'Psicologia' },
  { cod:'4.17',  desc:'Casas de repouso e de recuperação, creches, asilos e congêneres' },
  { cod:'4.18',  desc:'Inseminação artificial, fertilização in vitro e congêneres' },
  { cod:'4.19',  desc:'Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres' },
  { cod:'4.20',  desc:'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie' },
  { cod:'4.21',  desc:'Unidade de atendimento, assistência ou tratamento móvel e congêneres' },
  { cod:'4.22',  desc:'Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres' },
  { cod:'4.23',  desc:'Outros planos de saúde que se cumpram mediante serviços de terceiros contratados, credenciados, cooperados ou pagos pelo operador' },
  { cod:'5.01',  desc:'Medicina veterinária e zootecnia' },
  { cod:'5.02',  desc:'Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na área veterinária' },
  { cod:'5.03',  desc:'Laboratórios de análise na área veterinária' },
  { cod:'5.04',  desc:'Inseminação artificial, fertilização in vitro e congêneres na área veterinária' },
  { cod:'5.05',  desc:'Bancos de sangue e de órgãos e congêneres na área veterinária' },
  { cod:'5.06',  desc:'Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos na área veterinária' },
  { cod:'5.07',  desc:'Unidade de atendimento, assistência ou tratamento móvel e congêneres na área veterinária' },
  { cod:'5.08',  desc:'Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres' },
  { cod:'5.09',  desc:'Planos de atendimento e assistência médico-veterinária' },
  { cod:'6.01',  desc:'Barbearia, cabeleireiros, manicuros, pedicuros e congêneres' },
  { cod:'6.02',  desc:'Esteticistas, tratamento de pele, depilação e congêneres' },
  { cod:'6.03',  desc:'Banhos, duchas, sauna, massagens e congêneres' },
  { cod:'6.04',  desc:'Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas' },
  { cod:'6.05',  desc:'Centros de emagrecimento, spa e congêneres' },
  { cod:'7.01',  desc:'Ensino regular pré-escolar, fundamental, médio e superior' },
  { cod:'7.02',  desc:'Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza' },
  { cod:'7.03',  desc:'Elaboração e ministração de cursos e aulas de qualquer natureza' },
  { cod:'7.04',  desc:'Locação e operação de equipamentos para diversão, entretenimento e lazer' },
  { cod:'7.05',  desc:'Restauração, conservação e reparos de documentos, livros, revistas, jornais e outras publicações' },
  { cod:'8.01',  desc:'Hotéis, apart-hotéis, flat, hotéis residência, motéis, pensões e congêneres' },
  { cod:'8.02',  desc:'Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres' },
  { cod:'8.03',  desc:'Guias de turismo' },
  { cod:'9.01',  desc:'Agenciamento, corretagem ou intermediação de câmbio, seguros, cartões de crédito, planos de saúde e previdência privada' },
  { cod:'9.02',  desc:'Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer' },
  { cod:'9.03',  desc:'Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária' },
  { cod:'9.04',  desc:'Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil (leasing), de franquia (franchising) e de faturização (factoring)' },
  { cod:'9.05',  desc:'Agenciamento, corretagem ou intermediação de bens móveis ou imóveis, não abrangidos em outros itens desta lista' },
  { cod:'9.06',  desc:'Agenciamento marítimo' },
  { cod:'9.07',  desc:'Agenciamento de notícias' },
  { cod:'9.08',  desc:'Agenciamento de publicidade e propaganda, inclusive o agenciamento de veiculação por quaisquer meios' },
  { cod:'9.09',  desc:'Representação de qualquer natureza, inclusive comercial' },
  { cod:'9.10',  desc:'Distribuição de bens de terceiros' },
  { cod:'10.01', desc:'Guarda e estacionamento de veículos terrestres automotores, de aeronaves e de embarcações' },
  { cod:'10.02', desc:'Vigilância, segurança ou monitoramento de bens e pessoas' },
  { cod:'10.03', desc:'Escolta, inclusive de veículos e cargas' },
  { cod:'10.04', desc:'Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie' },
  { cod:'11.01', desc:'Exploração de cassinos, trens turísticos, parques de diversões, boates, shows, cinemas, auditórios, circos, feiras livres e congêneres' },
  { cod:'11.02', desc:'Exploração de delimitação de espaço para estacionamento de veículos' },
  { cod:'11.04', desc:'Produção, mediante ou sem encomenda prévia, de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais e festivais' },
  { cod:'12.01', desc:'Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres' },
  { cod:'12.03', desc:'Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres' },
  { cod:'12.04', desc:'Filmagem de festas e eventos' },
  { cod:'12.05', desc:'Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres' },
  { cod:'12.06', desc:'Reprografia, microfilmagem e digitalização' },
  { cod:'12.07', desc:'Composição gráfica, fotocomposição, clicheria, zincografia, litografia, fotolitografia' },
  { cod:'14.01', desc:'Lubrificação, limpeza, lustração, revisão, carga e recarga, conserto, restauração, blindagem, manutenção e conservação de máquinas, veículos, aparelhos e equipamentos' },
  { cod:'14.02', desc:'Assistência técnica' },
  { cod:'14.03', desc:'Recondicionamento de motores (exceto os de aeronaves)' },
  { cod:'14.04', desc:'Recauchutagem ou regeneração de pneus' },
  { cod:'14.05', desc:'Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, recorte e polimento de objetos quaisquer' },
  { cod:'14.06', desc:'Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial' },
  { cod:'14.07', desc:'Colocação de molduras e congêneres' },
  { cod:'14.08', desc:'Encadernação, gravação e douração de livros, revistas e congêneres' },
  { cod:'14.09', desc:'Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento' },
  { cod:'14.10', desc:'Tinturaria e lavanderia' },
  { cod:'14.11', desc:'Tapeçaria e reforma de estofamentos em geral' },
  { cod:'14.12', desc:'Funilaria e lanternagem' },
  { cod:'14.13', desc:'Carpintaria e serralheria' },
  { cod:'14.14', desc:'Guincho intramunicipal, guindaste e içamento' },
  { cod:'15.01', desc:'Administração de fundos quaisquer, de consórcio, de cartão de crédito ou débito e congêneres, de carteira de clientes, de cheques pré-datados e congêneres' },
  { cod:'15.02', desc:'Abertura de contas em geral, emissão, reemissão e fornecimento de avisos, comprovantes e documentos relacionados' },
  { cod:'15.03', desc:'Locação e manutenção de cofres particulares, de terminais eletrônicos, de terminais de atendimento e de bens e equipamentos em geral' },
  { cod:'15.04', desc:'Fornecimento de produto ou a prestação de serviços de crédito de qualquer modalidade' },
  { cod:'15.05', desc:'Emissão, reemissão, liquidação, alteração, cancelamento e baixa de ordens de pagamento, ordens de crédito e similares' },
  { cod:'15.06', desc:'Análise de risco para concessão de financiamento e empréstimos, emissão de garantias, bens e direitos' },
  { cod:'15.07', desc:'Emissão, reemissão, alteração, liquidação e cancelamento de câmbio, inclusive operações de câmbio de moedas estrangeiras' },
  { cod:'15.08', desc:'Estudo, análise e avaliação de crédito de qualquer natureza' },
  { cod:'15.09', desc:'Emissão, reemissão, alteração, cessão, substituição, cancelamento e registro de contrato de seguro, inclusive vida, saúde, acidente pessoal, previdência privada e títulos de capitalização' },
  { cod:'15.10', desc:'Custódia em geral, inclusive de títulos e valores mobiliários' },
  { cod:'15.11', desc:'Corretagem, inclusive de câmbio e de seguros' },
  { cod:'15.12', desc:'Cobrança por conta de terceiros, inclusive de direitos creditórios de qualquer natureza' },
  { cod:'15.13', desc:'Agenciamento e corretagem de contratos de leasing' },
  { cod:'15.14', desc:'Serviços relacionados ao depósito, à intermediação e à aplicação de capitais, inclusive valores mobiliários e câmbio' },
  { cod:'15.16', desc:'Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, cartão de débito, cartão salário e congêneres' },
  { cod:'15.17', desc:'Prestação de serviços de pagamento e similares previstos em legislação federal aplicável' },
  { cod:'16.01', desc:'Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros' },
  { cod:'16.02', desc:'Outros serviços de transporte de natureza municipal' },
  { cod:'17.01', desc:'Assessoria ou consultoria de qualquer natureza, não contida em outros itens desta lista' },
  { cod:'17.02', desc:'Análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações de qualquer natureza, inclusive cadastro e similares' },
  { cod:'17.03', desc:'Datilografia, digitação, estenografia, expediente, secretaria em geral, resposta audível, redação, edição, interpretação, revisão, tradução, apoio e infraestrutura administrativa e congêneres' },
  { cod:'17.04', desc:'Contabilidade, inclusive serviços técnicos e auxiliares' },
  { cod:'17.05', desc:'Advocacia' },
  { cod:'17.06', desc:'Arbitragem de qualquer espécie, inclusive jurídica' },
  { cod:'17.07', desc:'Auditoria' },
  { cod:'17.08', desc:'Análise de Organização e Métodos' },
  { cod:'17.09', desc:'Atuária e cálculos técnicos de qualquer natureza' },
  { cod:'17.10', desc:'Economia' },
  { cod:'17.11', desc:'Estatística' },
  { cod:'17.12', desc:'Cobrança em geral' },
  { cod:'17.13', desc:'Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção e gerenciamento de informações relacionados a operações de arrendamento mercantil ou de financiamentos' },
  { cod:'17.15', desc:'Meteorologia' },
  { cod:'17.16', desc:'Geologia' },
  { cod:'17.17', desc:'Engenharia, arquitetura, geologia, urbanismo, construção civil, manutenção, limpeza, meio ambiente, saneamento e congêneres' },
  { cod:'17.18', desc:'Topografia' },
  { cod:'17.19', desc:'Geofísica' },
  { cod:'17.20', desc:'Projetos, cálculos e desenhos técnicos de qualquer natureza' },
  { cod:'17.21', desc:'Aerofotogrametria (inclusive interpretação), cartografia, ortofotogrametria, radares, sonares, aerofotografia e congêneres' },
  { cod:'17.22', desc:'Pesquisa, geologia e prospecção de petróleo, água subterrânea e outros recursos minerais' },
  { cod:'17.23', desc:'Perícia, laudos, exames técnicos e análises técnicas' },
  { cod:'17.24', desc:'Planejamento, organização e administração de feiras, exposições, congressos e congêneres' },
  { cod:'18.01', desc:'Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros' },
  { cod:'19.01', desc:'Serviços de distribuição e geração de energia elétrica, gás, água e demais recursos naturais' },
  { cod:'20.01', desc:'Serviços de composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia e fotolitografia' },
  { cod:'21.01', desc:'Serviços de registros públicos, cartorários e notariais' },
  { cod:'22.01', desc:'Serviços de exploração de rodovias mediante cobrança de preço ou pedágio dos usuários' },
  { cod:'23.01', desc:'Serviços de programação e comunicação visual, desenho industrial e congêneres' },
  { cod:'24.01', desc:'Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres' },
  { cod:'25.01', desc:'Funerais, inclusive fornecimento de caixão, urna ou esquifes; aluguel de capela; transporte do corpo cadavérico; fornecimento de flores, coroas e outros paramentos' },
  { cod:'25.02', desc:'Embalsamamento e outros serviços afins' },
  { cod:'25.03', desc:'Planos ou convênio funerários' },
  { cod:'25.04', desc:'Manutenção e conservação de jazigos e cemitérios' },
  { cod:'25.05', desc:'Cessão de uso de espaços em cemitérios para sepultamento' },
  { cod:'26.01', desc:'Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios; courrier e congêneres' },
  { cod:'27.01', desc:'Serviços de assistência social' },
  { cod:'28.01', desc:'Serviços de avaliação de bens e serviços de qualquer natureza' },
  { cod:'29.01', desc:'Serviços de biblioteconomia' },
  { cod:'30.01', desc:'Serviços de biologia, biotecnologia e química' },
  { cod:'31.01', desc:'Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres' },
  { cod:'32.01', desc:'Serviços de desenhos técnicos' },
  { cod:'33.01', desc:'Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres' },
  { cod:'34.01', desc:'Serviços de investigações particulares, detetives e congêneres' },
  { cod:'35.01', desc:'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas' },
  { cod:'36.01', desc:'Serviços de meteorologia' },
  { cod:'37.01', desc:'Serviços de artistas, atletas, modelos e manequins' },
  { cod:'38.01', desc:'Serviços de museologia' },
  { cod:'39.01', desc:'Serviços de ourivesaria e lapidação (quando o material for fornecido pelo tomador do serviço)' },
  { cod:'40.01', desc:'Obras de arte sob encomenda' },
]
