[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."plano-lembrete"]
  schedule = "0 10 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
